[terminal.shell]
program = "/bin/zsh"

[window.padding]
x = 15
y = 15

[env]
WAYLAND_DISPLAY = "wayland-1"
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = true
title = "Alacritty"

[cursor]
style = "Beam"
unfocused_hollow = true

[font]
size = 12

[font.normal]
family = "NotoSansM Nerd Font Mono"
style = "Regular"

# [font.bold]
# family = "Monocraft Nerd Font"
# style = "Bold"
#
# [font.italic]
# family = "Monocraft Nerd Font"
# style = "Italic"


# Colors (Gruvbox dark)


[[colors.indexed_colors]]
color = "#fe8019"
index = 16

[[colors.indexed_colors]]
color = "#d65d0e"
index = 17

[[colors.indexed_colors]]
color = "#3c3836"
index = 18

[[colors.indexed_colors]]
color = "#504945"
index = 19

[[colors.indexed_colors]]
color = "#bdae93"
index = 20

[[colors.indexed_colors]]
color = "#ebdbb2"
index = 21

[colors.bright]
black   = "#6b6b6b"
red     = "#c55555"     # soft bright red
green   = "#aac474"     # muted bright green
yellow  = "#feca88"     # warm muted yellow
blue    = "#82b8c8"     # gentle bright blue
magenta = "#c28cb8"     # soft bright magenta
cyan    = "#8ac4c4"     # (approx â€“ some versions vary slightly here)
white   = "#d8d8d8"

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"

[colors.normal]
black = "0x1d2021"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xd5c4a1"
yellow = "0xfabd2f"

[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"
